name: build-core
on:
  push:
    branches:
      - main
    paths:
      - core-backend/**
  pull_request:
  workflow_dispatch:

jobs:
  build-core:
    name: Build Core
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3

      - name: 'Download latest JDK 17'
        run: wget https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz

      - name: 'Set up JDK'
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'jdkfile'
          jdkFile: jdk-17_linux-x64_bin.tar.gz
          cache: 'gradle'

      - name: 'Grant execute permission for gradlew'
        working-directory: ./core-backend
        run: chmod +x gradlew

      - name: 'Build with Gradle'
        working-directory: ./core-backend
        run: ./gradlew build --no-daemon
